name: 'Witness Configure'
description: 'Installs and configures Witness'
inputs:
  download-url:
    description: 'The URL to download the Witness binary'
    required: true
    default: "https://github.com/testifysec/witness/releases/download/test-archivist-003/witness"
  archivist-grpc-server:
    description: 'Archivist server address'
    required: true
    default: "archivist-grpc.testifysec.io:443"
  signing-key:
    description: 'PEM Encoded Signing Key'
    required: false
  step-name:
    description: 'The name of the step, defaults to the name of the job'
    required: false
  trace-enable:
    description: 'Enable tracing'
    required: false
    default: "false"
  attestors:
    description: 'List of attestors to use seperated by spaces'
    required: false
    default: "git env"
  
outputs:
  path:
    description: 'The path to the Witness binary'
runs:
  using: 'node16'
  main: 'index.js'
  