on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test witness install
    steps:
      - name: Witness install
        uses: testifysec/witness-install-action@main
        with:
          signing-key: |
            -----BEGIN PRIVATE KEY-----
            MC4CAQAwBQYDK2VwBCIEIN2GVZvD5a8M8ALX6ES0NV3zrNzi0ZwZ+DMJQykS92Lc
            -----END PRIVATE KEY-----
      - run: echo hello
        shell: shell.sh -- {0}