on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test witness install
    steps:
      - name: Witness install
        uses: testifysec/witness-install-action@v0.0.8
      - name: Test Witness
        run: echo "Hello World"
        shell: witness run -- {0}