on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test witness install
    steps:
      - name: Witness install
        uses: testifysec/witness-install-action@main
      - name: Test Witness
        run: witness