on: [push]

jobs:
  hello_world_job:
  
    runs-on: ubuntu-latest
    name: test witness install
    steps:
      - uses: actions/checkout@v3
      - name: Witness install
        uses: testifysec/witness-install-action@main
        with:
          signing-key: |
            -----BEGIN PRIVATE KEY-----
            MC4CAQAwBQYDK2VwBCIEIN2GVZvD5a8M8ALX6ES0NV3zrNzi0ZwZ+DMJQykS92Lc
            -----END PRIVATE KEY-----
          attestors: git environment
          trace-enable: "true"
          step-name: "test"
          archivist-grpc-server: "archivist-grpc.testifysec.io:443"
          download-url: "https://github.com/testifysec/witness/releases/download/test-archivist-003/witness"
      - run: ls -la /home/runner/.local/bin
      - run: ls -la /home/runner/
      - run: cat $HOME/.bash_profile
      - run: cat $HOME/.profile
      - run: cat $HOME/.bash_login
      - run: witness curl google.com

